[default]
# Sensitive configuration - DO NOT COMMIT TO VERSION CONTROL
# This file should be added to .gitignore

# Database secrets
DATABASE_PASSWORD = "renewmart_password"

# Security secrets
SECRET_KEY = "your-super-secret-key-change-this-in-production-make-it-long-and-random"

[production]
# Production secrets - these should be set via environment variables
# SECRET_KEY = "production-secret-key"
# DATABASE_PASSWORD = "production-database-password"

[development]
# Development secrets
SECRET_KEY = "dev-secret-key-not-for-production"
DATABASE_PASSWORD = "renewmart_password"